apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: n1euq8l4a-python
  janus-idp.io/tekton: n1euq8l4a-python
  backstage.io/kubernetes-id: n1euq8l4a-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: n1euq8l4a-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
