apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: n1euq8l4a-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: n1euq8l4a-python 
  name: n1euq8l4a-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: n1euq8l4a-python 
